fix(terraform): stop handle resource `for_each` as dynamic attribute (#4632)
This commit fixes an issue where Checkov crashes when a resource has the
following fields:
* A `for_each` with at least one variable like `for_each =
  toset([var.bar])`
* A dynamic block

Check the test resource file `main.tf` that comes with the commit if you
want more detail.

Checkov crashes with the following error:

```python
Error
Traceback (most recent call last):
  File "/home/antoine.rouaze/src/github.com/bridgecrewio/checkov/tests/terraform/graph/graph_builder/test_graph_builder.py", line 332, in test_build_graph_for_each_with_variables_and_dynamic_not_crash
    graph_manager.build_graph_from_source_directory(resources_dir)
  File "/home/antoine.rouaze/src/github.com/bridgecrewio/checkov/checkov/terraform/graph_manager.py", line 48, in build_graph_from_source_directory
    local_graph.build_graph(render_variables=render_variables)
  File "/home/antoine.rouaze/src/github.com/bridgecrewio/checkov/checkov/terraform/graph_builder/local_graph.py", line 78, in build_graph
    renderer.render_variables_from_local_graph()
  File "/home/antoine.rouaze/src/github.com/bridgecrewio/checkov/checkov/common/graph/graph_builder/variable_rendering/renderer.py", line 34, in render_variables_from_local_graph
    self._render_variables_from_edges()
  File "/home/antoine.rouaze/src/github.com/bridgecrewio/checkov/checkov/common/graph/graph_builder/variable_rendering/renderer.py", line 75, in _render_variables_from_edges
    self._edge_evaluation_task([edge_group])
  File "/home/antoine.rouaze/src/github.com/bridgecrewio/checkov/checkov/common/graph/graph_builder/variable_rendering/renderer.py", line 109, in _edge_evaluation_task
    self.evaluate_vertex_attribute_from_edge(inner_edges)
  File "/home/antoine.rouaze/src/github.com/bridgecrewio/checkov/checkov/terraform/graph_builder/variable_rendering/renderer.py", line 143, in evaluate_vertex_attribute_from_edge
    self.update_evaluated_value(
  File "/home/antoine.rouaze/src/github.com/bridgecrewio/checkov/checkov/terraform/graph_builder/variable_rendering/renderer.py", line 265, in update_evaluated_value
    self.local_graph.update_vertex_attribute(
  File "/home/antoine.rouaze/src/github.com/bridgecrewio/checkov/checkov/terraform/graph_builder/local_graph.py", line 466, in update_vertex_attribute
    self.vertices[vertex_index].update_attribute(
  File "/home/antoine.rouaze/src/github.com/bridgecrewio/checkov/checkov/common/graph/graph_builder/graph_components/blocks.py", line 173, in update_attribute
    additional_changed_attributes = self.extract_additional_changed_attributes(key)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine.rouaze/src/github.com/bridgecrewio/checkov/checkov/terraform/graph_builder/graph_components/blocks.py", line 64, in extract_additional_changed_attributes
    return self._extract_dynamic_changed_attributes(attribute_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/antoine.rouaze/src/github.com/bridgecrewio/checkov/checkov/terraform/graph_builder/graph_components/blocks.py", line 76, in _extract_dynamic_changed_attributes
    dynamic_block_name = dynamic_content_key_parts[-1]
                         ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
```

The issue occurs because the graph builder tries to extract dynamic
updated attributes from the resource `for_each`. As it's not a dynamic
block, the attribute doesn't have the proper depth (`for_each.my_var`
instead of `dynamic.for_each.my_var`), so it fails with an outbound
index error.

The commit fixes that by skipping the method
`_extract_dynamic_changed_attributes` if the current attribute is the
`for_each` of the resource. I might not have placed the precondition in
the right place as I don't know Checkov very well, so feel free to tell
me to move it—the same thing with the test.

fixes: #4324

Co-authored-by: ChanochShayner <57212002+ChanochShayner@users.noreply.github.com>