Multiline output support | Update `entrypoint.sh` (#1644)
* Update entrypoint.sh

Multiline `CHECKOV_RESULTS` fails.  That is because the set-output notation only works on single line input

* Update entrypoint.sh

Also make `CHECKOV_RESULTS` available to subsequent steps as and env variable

* validate env var set

Mitigate the following error to set env var
```
Error: Unable to process command '::set-env name=CHECKOV_RESULTS::|    | check_id                         | file            | resource                         | check_name                                   | guideline   |' successfully.
Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

* config file test

* config file test

* multiline output accessible via env var