Update setup-python GitHub Actions.md
We need to update the following action because not doing so will result on an error on certain architectures, see error below.

`Run actions/setup-python@v1
  with:
    python-version: 3.8
    architecture: x64
Error: Version 3.8 with arch x64 not found
Available versions: `

Version 4 of this action fixed the issue for me